SELECT quantity 
FROM ORDER_ITEMS
JOIN PRODUCTS ON ORDER_ITEMS.product_id = PRODUCTS.id 
WHERE PRODUCTS.id = 2456;

SELECT name  
FROM PRODUCTS
WHERE stock = 0;

select *
FROM ORDER_ITEMS
WHERE order_date IS NULL;

SELECT * 
FROM CUSTOMERS 
WHERE EMAIL LIKE'gmail.com'; 
